---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBa/ZWuDUqBlENPX4b/l3IjgYU1yIPQgkejUTem8ho9tEOWFgJ5bNnM9AjO+Qm1gjXaajtPxYE0FXEtS1r97tQVEG5GZZTkT3rVUCWzFRlmsAkOFcmXQ4emCgRiSrxYhd07tnt0kvEJ5WJPR3Yb3XCgTOGOd10NO3+NlVSwYxQJUPOsJnKuKKaQTImRfpbkiMnWFxHhN85HBfp7ekiX5jDCkMAX7Smzu4dr9rpc3TeB2xg0keYMiWG3t9IFpPqZfyNejiHLFgE0WbvEmmIj0BHhonJOgsObLMcTyZln5I9/bVJr8EF/ZwZGcro3S745dScXjJU6OuTB3satLj9RTOE3PGq7bzNilJUxvvsnyAGK9pzr2IqFHgqH8UPWChF5tvbDYnSWPGmkfqSRwtRI0QQ53E7vAzeQFr1IWPp1VI2e2KNnkol+Cbcymnmj6FsgzgD4QegAlXmqV8p3j6e/sE1a7w5V+4xPkQ57bjRqrJA9JTPltMM4UMWZWOc3G2AW0lgiSOulS+m925JhNalzW2tfWyhIOJyOQweWa0rsYe5f4d2y7BwyW2C2WwIpb7QaQj14CalbI0LYPvTZLEQbYfp0pODQ0c1Hbi2iEabAHX1GdAP3qmT4b8ch84KWvAJIlIAszDxA2gTNBdqlw/unhZ7pZQ51PfpW7dFiYfizZMNQ/Ii/Te2ymcslnI8KboI0WM70LiVIgB33VMmNdGcJCkJrqA==
    GF_SECURITY_ADMIN_USER: AgA/aT28pfFprv4OYg8fLIYZHynzx8rnPIp5bDcuLs3zux0ynsOPDH6FB7gClNGSXsS/oEHMda8/QAOT+M7xQJ6BrPnIiG2x9xd/REquyDlg/hb3vTAMnQtGiQZg7+ij576tTLuCuxNcyaONe7Hn4PJ1h+oJ2ygl4VPFlT0CLW4k0/x9wi2IgYupEAEmyqzm7AkMR4ZPtEkR+LmhYkQHB8DcnkrAsB3Rvkw4R2FyI5NyFIyClSOyGZs+rHh9jTp+/uwhTEWXh11lUA50Q3aPxqeMMP3AiCjatPk030mrwfjtlS//FwX7k8d6JLFimq2vO78QE3ZCAOrwIp5ASVIowEvCmjhlgCfDlx+Sb9Y/aIcDQZqznxtM6djSJafdFoY8JBWjFck+Ox5RzQKTKfeeqlHZdRgZCErsvUOtp9X4Nh6C7cq27DwIjtbiocuVcONnTNkrequU9Ghby5cBXIXC5WkksR3YMoBRMIr21pvEJgNMpHzLQojAc12C7yDhLL0AJVyX4GQYysVyycMLmXOM9doxnUN08QVEBnFgyJjqNTvXhWlG2kTmcID0TNv8Zj0S92FDuW6DTyTgwjZJgmPE8jeTOoCu3seOu/rUy0wBk90ArTl3U2RYo/elmnicQHTxAiJqQhNqrwzAc7FfZJR1AREmnTg2SbsH+byxduePErDkbDfz2+bSw1Ilt/smJhzvZ3y+tP/0XA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
